events {}

http {
    server {
        listen 10000;

        location / {
            proxy_pass http://azurite:10000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # CORS Заголовки
            add_header Access-Control-Allow-Origin * always;
            add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS, HEAD" always;
            add_header Access-Control-Allow-Headers "Authorization, Content-Type, x-ms-*, Accept" always;
            add_header Access-Control-Expose-Headers "x-ms-*" always;

            # Preflight (OPTIONS)
            if ($request_method = 'OPTIONS') {
                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS, HEAD";
                add_header Access-Control-Allow-Headers "Authorization, Content-Type, x-ms-*, Accept";
                add_header Content-Length 0;
                add_header Content-Type text/plain;
                return 204;
            }
        }
    }
}